name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create and Publish Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Make Distribution
        run: ./gradlew clean package -Prelease
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Release Asset
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./build/compose/binaries/*"]'
